stages:
  gridSearch:
    cmd: python src/models/gridsearch_rf.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - src/models/gridsearch_rf.py
    outs:
    - models/gridsearch_rf.pkl
  train:
    cmd: python src/models/train_rf.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - models/gridsearch_rf.pkl
    - src/models/train_rf.py
    outs:
    - models/train_rf.pkl
  evaluate:
    cmd: python src/models/evaluate_rf.py
    deps:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/y_test.csv
    - models/train_rf.pkl
    - src/models/evaluate_rf.py
    metrics:
    - metrics/accuracy.json:
        cache: false
